# Generated by Django 5.2.4 on 2025-07-08 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspapers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspaperpdf',
            name='date',
            field=models.DateField(default=datetime.date(2025, 7, 8)),
            preserve_default=False,
        ),
    ]
