# Generated by Django 5.2.4 on 2025-07-08 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspapers', '0002_newspaperpdf_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewspaperPDFPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='pdf_pages/')),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='newspapers.newspaperpdf')),
            ],
        ),
    ]
